# -*- coding: utf-8 -*-
"""BASE_Trabalho_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZLerTEby9RYeiXLqPMEwyr6BquEROB3

### Importar as Bibliotecas
"""

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import os

"""Ler os dados do arquivo do ensaio"""

f1t2 = pd.read_csv('/content/baja_front_rig1_carga_centro_turma2.txt', sep='\t', skiprows=10, encoding='latin1')
f1t2.set_index('Time (s)', inplace = True)
f1t2.rename(columns={"AI 1/AI 1 (m/s2)": "Acc1 m/s2", "AI 2/AI 2 (m/s2)": "Acc2 m/s2", "AI 3/AI 3 (V)": "Força (V)", "AI 4/AI 4 (V)": "Disp (V)" },  inplace = True)

"""Tabela dos dados lidos"""

f1t2

"""Gráfico da medição"""

fig, ax = plt.subplots(figsize=[8,6])

ax.plot(f1t2.index, f1t2['Acc1 m/s2'], 'k', label = 'Acc 1')
ax.plot(f1t2.index, f1t2['Acc2 m/s2'], 'r', label = 'Acc 2', alpha = 0.5)

"""Queremos caracterizar o amortecimento. Para isso, precisamos ver o decaimento da resposta. Entretanto, parte da resposta medida está muito relacionada à variação da entrada. Por isso, vamos verificar o decaimento apenas na parte final da resposta:"""

#Cortar região de interesse
u_np = np.array(f1t2.loc[3.1:4.25]['Acc1 m/s2'])
time_np = np.array(f1t2.loc[3.1:4.25].index) # Aligned time_np to u_np's range

# Plotando os resultados
fig = go.Figure()
fig.add_trace(go.Scatter(x=time_np, y=u_np, mode='lines', name='Acc1 m/s2 (Filtered)', line=dict(color='red')))

fig.update_layout(
    xaxis_title='Tempo(s)',
    yaxis_title='Aceleração (m/s^2)'
)

fig.show()

#omaga2222
